name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  swift-format:
    name: swift-format
    runs-on: ubuntu-latest
    container: swift:6.1
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: swift format lint --strict --recursive --parallel Sources Tests Examples Package.swift
